version: '3.8'

services:
  mcp-server:
    build: .
    container_name: wordpress-mcp-server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    volumes:
      # Mount .env file for configuration updates without rebuild
      - ./.env:/app/.env:ro
    # For stdio-based MCP, we don't need ports but keep it for future HTTP transport
    # The server will communicate via stdin/stdout by default
